export const rowData = [
  {  id: 1,
    title: "car",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 2,
    title: "bus",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 3,
    title: "truck",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 4,
    title: "van",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 5,
    title: "motar",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 6,
    title: "bike",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 7,
    title: "ship",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 8,
    title: "bullet bike",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 9,
    title: "honda",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},
{  id: 10,
    title: "boat",
    price:10,
    company:"Toyota",
    info: "one of the good car.",
    inCart: false,
    count: 1
},

]